spring:
  application:
    name: Desafio-San-Giorgio
  datasource:
    url: jdbc:postgresql://db_postgres:5432/san_giorgio
    username: postgres
    password: 900505
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        use_sql_comments: false

aws:
  sqs:
    fila:
      parcial: "fila-parcial"
      total: "fila-total"
      excedente: "fila-excedente"
  access:
    key: ${AWS_ACCESS_KEY:}
  secret:
    key: ${AWS_SECRET_KEY:}

